### ISSUE TITLE
WSJ is not working with bypass paywalls

### ISSUE THREAD

**Issue by sparklingwaterfall** [iamadamdev/bypass-paywalls-firefox#352]
WSJ is not working with bypass paywalls on Firefox. It seems to work on Chrome.

**Comment by nonissue** [comment]
Not working for me on Chrome or in Firefox. Looks like the `?mod=rsswn` workaround has been patched. 

I tried a few different methods I sometimes use for bypassing paywalls and none of them worked (google cache, facebook outlinking, private browsing mode, iOS user agent, wayback machine archive). Wonder if there's another work around.

**Comment by magnolia1234** [comment]
Do you have a weblink of article not working?
Wsj has Cxsense paywall redirects now, but this can be fixed.

**Comment by harshal-gajare** [comment]
Here is a sample url 

https://www.wsj.com/articles/carl-icahn-is-nearing-another-landmark-deal-this-time-its-with-his-son-11571457602

**Comment by magnolia1234** [comment]
Adding Wsj to googlebot setting (background.js) fixes paywall. Mod=rsswn has become obsolete then.

**Comment by sparklingwaterfall** [comment]
> 
> 
> Adding Wsj to googlebot setting (background.js) fixes paywall. Mod=rsswn has become obsolete then.

So how do I fix my own version?

**Comment by magnolia1234** [comment]
Wait for new release of @iamadamdev or use my (unsigned) fork https://github.com/magnolia1234/bypass-paywalls-firefox
You can use it on Android or desktop dev-version; allow unsigned addons).

**Comment by iamadamdev** [comment]
Fixed in latest version.

**Comment by dlichGH** [comment]
@iamadamdev 

> fixed in latest version

Install of v1.6.0 into FF v70.0 for Linux still gives the WSJ paywall.

Clearing all cookies does not fix it.

Uninstall then Reinstall does not fix it either.

Return to v1.5.9 does not help.

Checked it on three machines.  Same thing.

**Comment by iamadamdev** [comment]
Which article? Most work for me.

**Comment by ChopperDog** [comment]
Started working a couple of days ago and stopped again today.
https://www.wsj.com/articles/u-s-economy-grew-at-1-9-rate-in-third-quarter-11572438761?mod=rsswn

**Comment by magnolia1234** [comment]
All still works fije for me.
Fix dependant on googlebot as user agent.
Maybe you have a fixed user agent or you're using another extension which changes the user agent?

**Comment by magnolia1234** [comment]
Btw mod=rsswn is old way of bypassing Wsj paywall. Are you using latest v1.6.0 of extension?

**Comment by ChopperDog** [comment]
That was the problem, I was on 1.5.9. Thx for the help!

**Comment by msolorio79** [comment]
What does this mean, "Are you using latest v1.6.0 of extension?"  WSJ stopped working for me as well.  How can I update the extension? Any help is greatly appreciated!  :-)

**Comment by magnolia1234** [comment]
Check version in addons (and update).

**Comment by ChopperDog** [comment]
Click the bypass paywalls icon, click GitHub, click Getme>MD, click Download and install latest version.

Good Luck!

**Comment by magnolia1234** [comment]
Getme.MD, Mac-only?

**Comment by sparklingwaterfall** [comment]
smh...anyone getting washington post problems?
